default:
  server:
    port: "8080"
    host: "0.0.0.0"
    read_timeout: 30
    write_timeout: 30
    max_header_bytes: 1048576
  jwt:
    secret: "default_jwt_secret_change_in_production"
    expiration_hours: 168  # 7天 = 24 * 7
    refresh_expiration_hours: 720  # 30天
  database:
    type: "sqlite"
    dsn: "gobi.db"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300
    connection_pool:
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: 300
      conn_max_idle_time: 60
  security:
    bcrypt_cost: 12
    rate_limit: "100-M"  # 100 requests per minute
    cors_origins: ["http://localhost:3000", "http://localhost:5173"]
  logging:
    level: "info"
    format: "json"
    output: "stdout"
  cache:
    enabled: true
    ttl: 300  # 5 minutes
    max_size: 1000
    strategy:
      simple_query_ttl: 300   # 5 minutes for simple queries
      complex_query_ttl: 600  # 10 minutes for complex queries
      max_cache_size: 1000
      hot_cache_enabled: true
      hot_cache_ratio: 0.2    # 20% of items in hot cache
      promotion_threshold: 3   # Access count to promote to hot cache
      business_hours_start: 9
      business_hours_end: 17
      adaptive_ttl: true
      cache_warmup: true
      maintenance_interval: 300  # 5 minutes
      eviction_policy: "lru"     # lru, lfu, fifo
      compression_enabled: false
      metrics_enabled: true
  webhook:
    timeout: 30
    max_retries: 3
    retry_delay: 5

dev:
  server:
    port: "8080"
    host: "0.0.0.0"
    read_timeout: 30
    write_timeout: 30
    max_header_bytes: 1048576
  jwt:
    secret: "dev_jwt_secret_change_in_production"
    expiration_hours: 168  # 7天
    refresh_expiration_hours: 720  # 30天
  database:
    type: "mysql"
    dsn: "user:password@tcp(127.0.0.1:3306)/gobi?charset=utf8mb4&parseTime=True&loc=Local"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300
    connection_pool:
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: 300
      conn_max_idle_time: 60
  security:
    bcrypt_cost: 10
    rate_limit: "1000-M"  # 1000 requests per minute
    cors_origins: ["http://localhost:3000", "http://localhost:5173", "http://127.0.0.1:3000"]
  logging:
    level: "debug"
    format: "text"
    output: "stdout"
  cache:
    enabled: true
    ttl: 300  # 5 minutes
    max_size: 1000
    strategy:
      simple_query_ttl: 300   # 5 minutes for simple queries
      complex_query_ttl: 600  # 10 minutes for complex queries
      max_cache_size: 1000
      hot_cache_enabled: true
      hot_cache_ratio: 0.2    # 20% of items in hot cache
      promotion_threshold: 3   # Access count to promote to hot cache
      business_hours_start: 9
      business_hours_end: 17
      adaptive_ttl: true
      cache_warmup: true
      maintenance_interval: 300  # 5 minutes
      eviction_policy: "lru"     # lru, lfu, fifo
      compression_enabled: false
      metrics_enabled: true
  webhook:
    timeout: 30
    max_retries: 3
    retry_delay: 5

prod:
  server:
    port: "8080"
    host: "0.0.0.0"
    read_timeout: 30
    write_timeout: 30
    max_header_bytes: 1048576
  jwt:
    secret: "prod_jwt_secret_must_be_changed_in_production"
    expiration_hours: 24  # 1天
    refresh_expiration_hours: 168  # 7天
  database:
    type: "postgres"
    dsn: "host=localhost user=postgres password=pass dbname=gobi port=5432 sslmode=disable"
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 300
    connection_pool:
      max_open_conns: 100
      max_idle_conns: 10
      conn_max_lifetime: 300
      conn_max_idle_time: 120
  security:
    bcrypt_cost: 12
    rate_limit: "100-M"  # 100 requests per minute
    cors_origins: ["https://yourdomain.com", "https://app.yourdomain.com"]
  logging:
    level: "warn"
    format: "json"
    output: "file"
    file_path: "/var/log/gobi/app.log"
  cache:
    enabled: true
    ttl: 600  # 10 minutes
    max_size: 5000
    strategy:
      simple_query_ttl: 600   # 10 minutes for simple queries
      complex_query_ttl: 1800 # 30 minutes for complex queries
      max_cache_size: 5000
      hot_cache_enabled: true
      hot_cache_ratio: 0.15   # 15% of items in hot cache
      promotion_threshold: 5   # Access count to promote to hot cache
      business_hours_start: 9
      business_hours_end: 17
      adaptive_ttl: true
      cache_warmup: true
      maintenance_interval: 600  # 10 minutes
      eviction_policy: "lru"     # lru, lfu, fifo
      compression_enabled: true
      metrics_enabled: true
  webhook:
    timeout: 30
    max_retries: 5
    retry_delay: 10

test:
  server:
    port: "8081"
    host: "localhost"
    read_timeout: 10
    write_timeout: 10
    max_header_bytes: 1048576
  jwt:
    secret: "test_jwt_secret"
    expiration_hours: 1
    refresh_expiration_hours: 24
  database:
    type: "sqlite"
    dsn: ":memory:"
    max_open_conns: 1
    max_idle_conns: 1
    conn_max_lifetime: 60
    connection_pool:
      max_open_conns: 1
      max_idle_conns: 1
      conn_max_lifetime: 60
      conn_max_idle_time: 30
  security:
    bcrypt_cost: 4
    rate_limit: "1000-M"
    cors_origins: ["http://localhost:3000"]
  logging:
    level: "error"
    format: "text"
    output: "stdout"
  cache:
    enabled: false
    ttl: 60
    max_size: 100
    strategy:
      simple_query_ttl: 60    # 1 minute for simple queries
      complex_query_ttl: 120  # 2 minutes for complex queries
      max_cache_size: 100
      hot_cache_enabled: false
      hot_cache_ratio: 0.1    # 10% of items in hot cache
      promotion_threshold: 2   # Access count to promote to hot cache
      business_hours_start: 9
      business_hours_end: 17
      adaptive_ttl: false
      cache_warmup: false
      maintenance_interval: 60  # 1 minute
      eviction_policy: "fifo"   # lru, lfu, fifo
      compression_enabled: false
      metrics_enabled: false
  webhook:
    timeout: 5
    max_retries: 1
    retry_delay: 1 